### ISSUE TITLE
Billboards to-do and discussion

### ISSUE THREAD

**Issue by Alan-FGR** [AtomicGameEngine/AtomicGameEngine#1601]
# Aligned
- [ ] create discrete chunks of vbos (static)
- [ ] pass x, y, z, yangle to the shader
- [ ] calculate vertices positions in the vertex shader
- [ ] calculate uv tile in the vertex shader
- [ ] zero vbo vertices of billboards that shouldn't be displayed
- [ ] create and dispose vbos
- [ ] cull vbos using aabbs
- [ ] use a 'faderange' or 'fadestart' shader constant in the vertex shader and calculate a 'transition' amount
- [ ] use the transition amount in the pixel shader to apply a dither effect

# Free Billboards
TODO

**Comment by Alan-FGR** [comment]
Using the camera quat for the orientations was a dumb idea... I've fixed that by using a mat3x3 representing the rotation of the camera->imposter vector, it's calculated for each vertex (from the node position passed in the vbo) so it isn't as efficient as just multiplying by the camera rot quat, but at least it works properly now.

In terms of performance I still couldn't reach the limits even on the slowest GPU I have handy here, I kept adding them, until I had millions and ran outta ram because of the nodes... later on I'm going to try on an Intel G41...

On a related note I'm tackling the aligned imposters because it's going to be used in a game, later on I'm going to finish the free imposters, it's going to be even easier now that we have a rotation matrix, so we just gotta pass the node matrix and multiply (it's never as easy as the plan though :P )

**Comment by Alan-FGR** [comment]
I'm facing two problems, one is major and beyond my control, another will probably have to be workarounded:

1 - Using the draw distance culling to toggle the meshes is too slow... I thought it would be possible to use this but it isn't, having many objects, even culled out hogs the CPU too much, possibly because the core checks the distance for each one of them individually as opposed to some spatially optimized broad phase culling. The impostors are infinitely fast :P but that doesn't matter if the rendering subsystem hogs your CPU just not to draw the originals.

2 - Origin shift correction is hard! The attached binary has origin shift but although the math seems fine for some angles it doesn't match the original very well... it's probably some transformation I'm doing wrong, perhaps wrong composition order, but I don't have the time to debug that because iteration times are slow and I'd have to move the math to a prototyping platform that allows me to plot stuff and possibly shamefully curve-fit it... shaders are too bad for testing since it's hard to get debug info other than with colors and that kinda stuff, so for the mean time I'm going to use another approach that is calculating the center from the object's aabb and placing the impostor off-center... at least it's going to look OK but anchoring will be centered on the impostor center not the object anchor, what shouldn't be a problem for the current usage which is for objects far away.

Also, I still need help with rendering the impostors textures properly, including normals and shadow maps: using the gbuffer isn't the best options because we'll need special deferred shaders to pass the normals mapped onto the objects to the final render buffer. The current generation code is not good too since it's alphaing black pixels...

Test debug build:
[Debug.zip](https://github.com/AtomicGameEngine/AtomicGameEngine/files/1212019/Debug.zip)
NOTE: change the quantity of imposters in the qty.txt file

**Comment by Alan-FGR** [comment]
Also, is there any example on how to procedurally create texture arrays?

**Comment by Alan-FGR** [comment]
I think the problem with distance testing could be solved by using a separated frustum culling to cull the "imposterized" objects, thus taking total advantage of spatial optimization.

**Comment by Alan-FGR** [comment]
After failing miserably to programmatically create the material, technique, texture array, shader, and link it all together, I'm just going to write xml/image files and read them in the engine... that will also serve for 'caching' so you only have to do it once and subsequently read from disk if it's there... docs/sscce on how to programmatically do that would be appreciated nevertheless... maybe in our wiki or something so it helps other people too

**Comment by Alan-FGR** [comment]
It's almost ready now: https://github.com/Alan-FGR/FileSharing/blob/master/Debug.7z

**Comment by Alan-FGR** [comment]
Do other collaborators even get notifications for **these**?

**Comment by Alan-FGR** [comment]
https://github.com/Alan-FGR/FileSharing/blob/master/Debug2.7z

**Comment by Alan-FGR** [comment]
![_zou](https://user-images.githubusercontent.com/8399299/29325304-867b21c8-81bd-11e7-92ea-155df49e3fcd.gif)
![_mas](https://user-images.githubusercontent.com/8399299/29325331-9b635614-81bd-11e7-951c-90865d5c1951.gif)
